# labeler "full" schema

# enable labeler on issues, prs, or both.
enable:
  issues: false
  prs: true
# comments object allows you to specify a different message for issues and prs

comments:
  prs: |
    PR 작성하느라 고생 많았어요!! 라벨 잘 지정되었는지 확인 한 번 해 주기 🫶

# Labels is an object where:
# - keys are labels
# - values are objects of { include: [ pattern ], exclude: [ pattern ] }
#    - pattern must be a valid regex, and is applied globally to
#      title + description of issues and/or prs (see enabled config above)
#    - 'include' patterns will associate a label if any of these patterns match
#    - 'exclude' patterns will ignore this label if any of these patterns match
labels:
  ':bug: bug':
    include:
      - '\bBug\b'
  ':sparkles: feature':
    include:
      - '\bFeature\b'
  ':blue_book: documentation':
    include:
      - '\bDocs\b'
  ':package: chore':
    include:
      - '\bChore\b'
  ':framed_picture: design':
    include:
      - '\bDesign\b'
  ':test_tube: test':
    include:
      - '\bTest\b'
  ':toolbox: refactor':
    include:
      - '\bRefactor\b'
  ':package: ci/cd':
    include: ['\bCI\/CD\b', '\bCI\b', '\bCD\b']
