import {
  IcDesignerRecruit1,
  IcDesignerRecruit10,
  IcDesignerRecruit11,
  IcDesignerRecruit2,
  IcDesignerRecruit3,
  IcDesignerRecruit4,
  IcDesignerRecruit5,
  IcDesignerRecruit6,
  IcDesignerRecruit7,
  IcDesignerRecruit8,
  IcDesignerRecruit9,
  IcLogoDailyMorning,
  IcLogoStudioEdink,
  IcLogoStunning,
} from "../../assets";
import ImgActiveRecruit1 from "../../assets/img/img_active_recruit_1.png";
import ImgActiveRecruit2 from "../../assets/img/img_active_recruit_2.png";
import ImgActiveRecruit3 from "../../assets/img/img_active_recruit_3.png";
import ImgDesignerRecruit1 from "../../assets/img/img_designer_recruit_1.png";
import ImgDesignerRecruit10 from "../../assets/img/img_designer_recruit_10.png";
import ImgDesignerRecruit11 from "../../assets/img/img_designer_recruit_11.png";
import ImgDesignerRecruit2 from "../../assets/img/img_designer_recruit_2.png";
import ImgDesignerRecruit3 from "../../assets/img/img_designer_recruit_3.png";
import ImgDesignerRecruit4 from "../../assets/img/img_designer_recruit_4.png";
import ImgDesignerRecruit5 from "../../assets/img/img_designer_recruit_5.png";
import ImgDesignerRecruit6 from "../../assets/img/img_designer_recruit_6.png";
import ImgDesignerRecruit7 from "../../assets/img/img_designer_recruit_7.png";
import ImgDesignerRecruit8 from "../../assets/img/img_designer_recruit_8.png";
import ImgDesignerRecruit9 from "../../assets/img/img_designer_recruit_9.png";

export const activeRecruitList = [
  {
    id: 0,
    imgSrc: ImgActiveRecruit1,
    position: "인턴",
    title: "노트폴리오 콘텐츠 팀 채용",
    place: "서울시 마포구",
    info: "노트폴리오 커뮤니티 팀은 ‘노트폴리오의 기둥’이라고 말할 수 있을 정도로 노트폴리오 서비스에서 가장 큰 부분...",
    companyLogo: <IcLogoStunning />,
    company: "스터닝",
    endTime: "채용시 마감",
  },
  {
    id: 1,
    imgSrc: ImgActiveRecruit2,
    position: "경력(2년~6년)",
    title: "그래픽 편집 디자이너 채용",
    place: "서울시 송파구",
    info: "스튜디오에딩크에서 긍정적인 마인드와 자세로 함께 성장해나갈 역량있는 디자이너를 모집합니다.",
    companyLogo: <IcLogoStudioEdink />,
    company: "스튜디오에딩크",
    endTime: "채용시 마감",
  },
  {
    id: 2,
    imgSrc: ImgActiveRecruit3,
    position: "경력 무관",
    title: "그래픽디자이너 채용",
    place: "서울시 마포구",
    info: "일상의실천에서 그래픽디자이너를 찾습니다. 일상의실천은 그래픽디자인의 경계를 확장하여 시각언어의 새로운...",
    companyLogo: <IcLogoDailyMorning />,
    company: "일상의실천",
    endTime: "2024.05.17 까지",
  },
];

export const chipsTextList = [
  "전체",
  "UX 디자이너",
  "캐릭터 디자이너",
  "패션 디자이너",
  "BI/BX 디자이너",
  "패키지 디자이너",
  "그래픽 디자이너",
  "아트 디렉터",
  "콘텐츠 디자이너",
  "신입 디자이너",
  "영상, 모션 디자이너",
  "일러스트레이터",
  "인테리어 디자이너",
  "편집 디자이너",
  "UI, GUI 디자이너",
  "3D 디자이너",
  "공간 디자이너",
];

export const designerRecruitList = [
  {
    id: 0,
    imgSrc: ImgDesignerRecruit1,
    position: "경력 무관",
    title: "위마트 디자이너",
    place: "서울시 광진구",
    endTime: "채용시 마감",
    companyLogo: <IcDesignerRecruit1 />,
    company: "위마트",
  },
  {
    id: 1,
    imgSrc: ImgDesignerRecruit2,
    position: "경력 무관",
    title: "프레젠테이션(PPT) 디자이 모집",
    place: "서울시 구로구",
    endTime: "채용시 마감",
    companyLogo: <IcDesignerRecruit2 />,
    company: "원포인트",
  },
  {
    id: 2,
    imgSrc: ImgDesignerRecruit3,
    position: "경력(3년~7년)",
    title: "디자이너 채용",
    place: "광주광역시 북구",
    endTime: "채용시 마감",
    companyLogo: <IcDesignerRecruit3 />,
    company: "바른핑거스 주식회사",
  },
  {
    id: 3,
    imgSrc: ImgDesignerRecruit4,
    position: "경력 무관",
    title: "그래픽디자이너 채용",
    place: "서울시 마포구",
    endTime: "2024.05.17 까지",
    companyLogo: <IcDesignerRecruit4 />,
    company: "일상의 실천",
  },
  {
    id: 4,
    imgSrc: ImgDesignerRecruit5,
    position: "경력 무관",
    title: "코엑스 브랜드 디자인 담당 채용",
    place: "서울시 강남구",
    endTime: "2024.05.12 까지",
    companyLogo: <IcDesignerRecruit5 />,
    company: "(주)피엔에이링크",
  },
  {
    id: 5,
    imgSrc: ImgDesignerRecruit6,
    position: "경력 무관",
    title: "슈피겐코리아 경력 및 채용연계...",
    place: "서울시 강남구",
    endTime: "2024.05.06 까지",
    companyLogo: <IcDesignerRecruit6 />,
    company: "슈피겐코리아",
  },
  {
    id: 6,
    imgSrc: ImgDesignerRecruit7,
    position: "경력(1년~2년)",
    title: "시각디자이너 채용",
    place: "재택근무",
    endTime: "채용시 마감",
    companyLogo: <IcDesignerRecruit7 />,
    company: "하루디자인",
  },
  {
    id: 7,
    imgSrc: ImgDesignerRecruit8,
    position: "경력(3년~9년)",
    title: "출판 편집 디자이너 채용",
    place: "서울시 서초구",
    endTime: "상시 채용",
    companyLogo: <IcDesignerRecruit8 />,
    company: "메가스터디",
  },
  {
    id: 8,
    imgSrc: ImgDesignerRecruit9,
    position: "경력 무관",
    title: "컨텐츠 디자이너 채용",
    place: "서울시 강남구",
    endTime: "상시 채용",
    companyLogo: <IcDesignerRecruit9 />,
    company: "(주) 트레이블",
  },
  {
    id: 9,
    imgSrc: ImgDesignerRecruit10,
    position: "인턴",
    title: "노트폴리오 콘텐 매니저(인턴)...",
    place: "서울시 마포구",
    endTime: "채용시 마감",
    companyLogo: <IcDesignerRecruit10 />,
    company: "에이블리 코퍼레이션",
  },
  {
    id: 10,
    imgSrc: ImgDesignerRecruit11,
    position: "경력(3년~6년)",
    title: "경력 UI/UX 디자이너 채용",
    place: "서울시 영등포구",
    endTime: "채용시 마감",
    companyLogo: <IcDesignerRecruit11 />,
    company: "디엘스",
  },
  {
    id: 11,
    imgSrc: ImgDesignerRecruit11,
    position: "신입",
    title: "신입 UI/UX 디자이너 채용",
    place: "서울시 영등포구",
    endTime: "채용시 마감",
    companyLogo: <IcDesignerRecruit11 />,
    company: "디엘스",
  },
];
