import { IcMog, IcKinder, IcMolly, IcStudio, IcFloggy, IcView, IcGreyHeart } from "../../assets/index";

export const bestfolioHomeList = [
  {
    id: 0,
    imgSrc: "/src/assets/img/img_bestfolio_home_1.png",
    name: "모그 스튜디오",
    companyLogo: <IcMog />,
    viewLogo: <IcView />,
    view: 1,
    like: 1,
    greyHeartLogo: <IcGreyHeart />,
  },
  {
    id: 1,
    imgSrc: "/src/assets/img/img_bestfolio_home_2.png",
    name: "킨더가든",
    companyLogo: <IcKinder />,
    viewLogo: <IcView />,
    view: 1,
    like: 1,
    greyHeartLogo: <IcGreyHeart />,
  },
  {
    id: 2,
    imgSrc: "/src/assets/img/img_bestfolio_home_3.png",
    name: "몰리(Molly)",
    companyLogo: <IcMolly />,
    viewLogo: <IcView />,
    view: 1,
    like: 1,
    greyHeartLogo: <IcGreyHeart />,
  },
  {
    id: 3,
    imgSrc: "/src/assets/img/img_bestfolio_home_4.png",
    name: "스튜디오 디워크",
    companyLogo: <IcStudio />,
    viewLogo: <IcView />,
    view: 1,
    like: 1,
    greyHeartLogo: <IcGreyHeart />,
  },
  {
    id: 4,
    imgSrc: "/src/assets/img/img_bestfolio_home_5.png",
    name: "Floggy",
    companyLogo: <IcFloggy />,
    viewLogo: <IcView />,
    view: 1,
    like: 1,
    greyHeartLogo: <IcGreyHeart />,
  },
];
